### ISSUE TITLE
Add hetu generator

### ISSUE THREAD

**Issue by goalaleo** [bittisiirto/henkilotunnus#1] opened 2018-11-07 13:45 UTC
It would be nice if there was a way to generate valid hetus for testing/seeds.
If there is a uniqueness validation applied to a hetu - as there usually is - creating fake users currently requires manual calculation of valid hetus (or, if done programmatically, accessing the constants from outside of `Hetu`).

### Suggestion
Add a `Henkilotunnus::Hetu.generate` method that returns valid hetus. There could be optional arguments such as `date` or `date_range`, and `person_number`.

Adding some optional arguments would ensure that there are no accidental hetu collisions - resulting in nondeterministic test failures - by using something like [FactoryBot's sequence](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#sequences)) on the person number like so:
```
factory :user do
  sequence(:hetu) { |n| Hetu.generate(person_number: n) }
end
```

It should be pretty easy to implement this using the existing code, so I can do it if you think that it's a good addition.

**Comment by alexhanh** [comment] 2018-11-08 18:11
Good idea and makes sense. :thumbsup: Please feel free to implement.

**Comment by alexhanh** [comment] 2018-11-13 01:57
Not sure if these are really improvements (certainly debatable), but here are a few ideas open for discussion:

- Breaking the implementation into several small snippets of code and methods increases testability, reusability, decoupling and sometimes readability. However, it also bloats the public API of the class. Personally, not a fan of "micro methods" (unless there's a clear reason, like reusability or testing) - prefer simply inlining. For example, having a `century` or `date_limits` methods as public methods in the Hetu class doesn't make too much sense to me. Sure they could be made private, but inlining them is fine, I think.

- The `initialize` method could have an alternative version that takes date of birth and person number, and then handles the century sign and checksum. This way `generate` doesn't need to care about that. Alternatively, most of the generate -method's implementation could be moved into `initialize` and simply call that then from `generate` instead.

- Could argument handling be improved? Perhaps the issue is that looking at the `generate` method, it isn't instantly obvious what the relevant arguments are - you have to recurse through the methods to gather the whole picture (ie. the arguments are hiding under the method hierarchy, which is not optimal). Also, is `**kwargs` type of argument passing a recommended practice in Ruby? Here's what Ruby style guide has to say about argument passing https://github.com/rubocop-hq/ruby-style-guide#optional-arguments. The very least, it should be considered that the double splat operator was introduced in Ruby 2.x. Without it, this gem could work under Ruby 1.9, I believe. So `generate(person_number: ..., date: ...)` or `generate(opts = {})` should be considered.

- Not sure about the need for start and end dates as arguments, since choosing a random date between certain time range can be done by the caller, if necessary. Do you have a specific use case for this in mind?

**Comment by goalaleo** [comment] 2018-11-13 13:17
@alexhanh thanks for the feedback. Those suggestions make sense - I'll make some changes based on them

**Comment by alexhanh** [comment] 2018-11-14 15:22
Looks good, merged https://github.com/bittisiirto/henkilotunnus/commit/b9b6b83c3b11b33c0c71db04896ed1acd6e5c6b9.

Thank you for contributing!

**Closed as completed by alexhanh** 2018-11-14 15:22 UTC
